### PR TITLE
Enabling Facet Pivot Fields support in the Scala Sole library

### PR DESCRIPTION
**Pull request by Ukjain**
Hey Zoe,

Pivot support was missing in the current library. Please accept my pull request which enables the pivot support for this library

### CODE REVIEW

**Comment by takezoe** [comment]
@Ukjain Sorry for my late response! This pull request conflicts with the current master branch. Could you resolve it?

**Comment by Ukjain** [comment]
@takezoe please check now. I have solved the merge conflict

**Comment by takezoe** [comment]
OK! Thanks for your contribution. I will publish the next version.

**Comment by palak21** [comment]
@takezoe : Please publish next version.

**Pull request merged**
