### PR TITLE
Added support for grouping (facet groups, group limit) and qTime in t…

### PR DESCRIPTION
**Pull request by satheeshakkinepally**
…he response

### CODE REVIEW

**Comment by takezoe** [comment]
@satheeshakkinepally Cool! Thanks for a pull request!

**Comment by satheeshakkinepally** [comment]
Thanks @takezoe . When are you planning for a next build? 0.0.19? 
When i try 0.0.18-SNAPSHOT, my build does not seem to be getting the latest changes and hence am asking for a new build 0.0.19

**Comment by satheeshakkinepally** [comment]
Also, there are a lot of attributes missing from being set directly to SolrQuery in solrj. SolrJ provides support to set facet attribute fields at each field level. 
Example:- solrQuery.set("f." + field + ".facet.sort", "count");
Most of the nontrivial solrj clients make heavy use of them and the scala client restricts such usage and do not support it. Any chance you want to support that anytime soon? I would like to take it up. 
Let me know. Also am curious to know how many users do you have for this library

**Comment by takezoe** [comment]
> When are you planning for a next build? 0.0.19?

I'm going to release it shortly.

> Also, there are a lot of attributes missing from being set directly to SolrQuery in solrj. SolrJ provides support to set facet attribute fields at each field level.

This library was created to satisfy requirements in our system originally. It works for our system well, but if you need extra features, pull requests are welcome! I will take them.

In my opinion, adding a method to touch SolrQuery might be useful as an ultimate workaround when users need unimplemented methods.

**Comment by satheeshakkinepally** [comment]
Thank You! I need a lot more from this library to make it useful for our system. I will work on opening more pull requests

Thanks again

**Pull request merged**
