### PR TITLE
async-http-client 2.0.24 -> 2.0.37

### PR DESCRIPTION
**Pull request by masahitojp**
fix a security vulnerability of async-http-client.
See below link(at later async-http-client 2.0.35, fix a security vulnerability.)

https://github.com/AsyncHttpClient/async-http-client/issues/1455

### CODE REVIEW

**Comment by takezoe** [comment]
@masahitojp Thanks for pull request! Do you need a new release?

**Comment by masahitojp** [comment]
@takezoe Yes, We need a new release for fix a security vulnerability!

**Comment by takezoe** [comment]
OK, I will publish as soon as possible.

**Comment by takezoe** [comment]
@masahitojp Published 0.0.16.

**Pull request merged**
